### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by avidraghav** [avidraghav/MyNotes#26]
The styling of Shown Tasks is very basic, improve it by changing the delete icon style, font style etc.
<img width="407" alt="Screenshot 2022-03-20 at 4 22 26 PM" src="https://user-images.githubusercontent.com/49483235/159158846-e3bbd973-a2d1-46ec-a8d4-54a5d4f4bbd1.png">

**Comment by xoxo16** [comment]
pls assign this issue to me

**Comment by avidraghav** [comment]
There you go :)

**Comment by xoxo16** [comment]
is this issue hacktober fest accepted

**Comment by avidraghav** [comment]
yes, it is

**Comment by xoxo16** [comment]
https://www.figma.com/file/6t158AQBvuFo0PLnlVlLrf/Untitled?node-id=0%3A1

Above is the link for figma file pls check this out

**Comment by avidraghav** [comment]
There is no option currently for searching notes/todos, also no sub-categories such as Recent, Favourites and Shared with Me. How will incorporate the design?
Do you wish to add the above mentioned feature too?

**Comment by xoxo16** [comment]
https://www.figma.com/file/6t158AQBvuFo0PLnlVlLrf/Untitled?node-id=0%3A1

This is the new design of the app.

**Comment by avidraghav** [comment]
Sort by Deadline View should be a toggle/Checkbox button, the user should understand that he can switch back and forth between sorting the tasks based on deadline.
Also there is no need for the showing the notes separately in horizontal scrolling at top, also please don't add any external icons as they will increase the size of the project.

**Comment by avidraghav** [comment]
The color scheme looks good though, please take your time and try to do something simple by following Material guidlines 😄

**Comment by xoxo16** [comment]
https://www.figma.com/file/6t158AQBvuFo0PLnlVlLrf/Untitled?node-id=0%3A1

This is purely made according to your app.

**Comment by avidraghav** [comment]
This looks good, go ahead!

**Comment by xoxo16** [comment]
So should i make pull request or you need any more changes in the design?

**Comment by avidraghav** [comment]
Please also remove that 'Notes' text on the top looks unnecessary. Go ahead
with the PR then.

**Comment by xoxo16** [comment]
https://www.figma.com/file/6t158AQBvuFo0PLnlVlLrf/Untitled?node-id=0%3A1


Can you please check this once

**Comment by avidraghav** [comment]
Please remove this extra space between toolbar and and the deadline
<img width="326" alt="Screenshot 2022-10-02 at 4 23 19 PM" src="https://user-images.githubusercontent.com/49483235/193450408-7878f5a7-afde-43d4-8c52-db9073560423.png">

**Comment by xoxo16** [comment]
Done

**Comment by rishujam** [comment]
@avidraghav when will you add more issues

**Comment by avidraghav** [comment]
You are free to raise an issue or enhancement that u think can benefit the app. @rishujam

**Comment by rishujam** [comment]
I think now we have a basic todo app just need better ui. Can we add a frequency/time attribute in the task. For example an exercise for 30 min (time) or Eat banana 4 (frequency). Should I create this issue ? @avidraghav

**Comment by xoxo16** [comment]
hey  i am currently working on ui of the app @rishujam

**Comment by rishujam** [comment]
@xoxo16 Yes, I was asking if we can add that feature

**Comment by avidraghav** [comment]
@rishujam please restrict your queries, doubts to the issues assigned to you. This is not a thread for discussion.

**Comment by avidraghav** [comment]
@xoxo16 when I can expect a PR for this task? Any expected time of delivery?

**Comment by xoxo16** [comment]
I have just raised a PR and committed the required changes. can u please see to it and if there is any problem please let me know about it

**Comment by avidraghav** [comment]
You haven't made any changes to the XML layouts in the app which is indeed the actual task, have you done android development before?

**Comment by xoxo16** [comment]
no I haven't done android development before. in fact, this is the first time I am using GitHub

**Comment by avidraghav** [comment]
I'll then advise you to first learn Android Development and then starting contributing to Android projects.

**Comment by xoxo16** [comment]
I thought it was just a design task so i did it and thank you for your advice
