### ISSUE TITLE
Implement Undo When Deleting a Task

### ISSUE THREAD

**Issue by avidraghav** [avidraghav/MyNotes#31]
Add an Undo Action in The Snackbar which is displayed when a task is deleted to revert the action

**Comment by rishujam** [comment]
Hey can I work on this

**Comment by rishujam** [comment]
I have added the functionality should I create a new branch ?

**Comment by avidraghav** [comment]
Hi, please raise a PR :)

**Comment by rishujam** [comment]
Done. This is my first contribution if something wrong in PR please let me know.

**Comment by avidraghav** [comment]
Thanks for the contribution Sudhanshu, will let u know after the PR review :)

**Comment by avidraghav** [comment]
closed by #52
