### ISSUE TITLE
Needless Assignment in Collect

### ISSUE THREAD

**Issue by ravi-kumar7** [avidraghav/MyNotes#4]
https://github.com/avidraghav/MyNotes/blob/624946c017a9560b51ac571178ac95eb83500847/app/src/main/java/com/raghav/mynotes/ui/AllTasksVM.kt#L25

Assigning Resource.Loading() to _task variable in the collect lambda does nothing as you are immediately assigning Success to it. Move it outside the scope.

**Comment by avidraghav** [comment]
Yes, are you willing to fix this by raising a PR?

**Comment by ravi-kumar7** [comment]
Yes, will do it. Thanks @avidraghav.
