### ISSUE TITLE
Add Up Button in the Action Bar for AllTasksFragment

### ISSUE THREAD

**Issue by avidraghav** [avidraghav/MyNotes#46]
The App has single activity (`MainActivity`) and this activity's action bar is used for both the fragments which are inflated inside it.
The task is to implement action bar for both fragments and setup a conditional navigation in which an Up Button 
<img width="50" alt="Screenshot 2022-04-25 at 1 01 25 PM" src="https://user-images.githubusercontent.com/49483235/165041183-b4701256-f5f2-4d18-805c-7889220b6603.png"> 
is showed in the action bar of `AddTaskFragment` but not in the action bar of `AllTasksFragment`

The usage of a Up Button is that it should navigate a user back to previous destination of the app he visited but not exit the app
https://developer.android.com/guide/navigation/navigation-principles

**Comment by thisrahul** [comment]
Can i do this?

**Comment by avidraghav** [comment]
Yup sure go ahead!

**Comment by thisrahul** [comment]
Okay,Thank you

**Comment by thisrahul** [comment]
Hello sir, i was implement thsi issue here is a video :
https://user-images.githubusercontent.com/52368582/193449776-c70b4abd-4edc-4ec1-8e58-e81997960da7.mp4

Also i make a pr for this issue
(I am participating in Hacktoberfest so please accept my pr with that manner)

**Comment by thisrahul** [comment]
Hello sir, i was implement thsi issue here is a video :
https://user-images.githubusercontent.com/52368582/193449776-c70b4abd-4edc-4ec1-8e58-e81997960da7.mp4

Please check and let me know if is there any changes required.

**Comment by thisrahul** [comment]
Sir can i make a pr for this?

**Comment by avidraghav** [comment]
As I saw you already made one for this issue but closed it yourself. If you can solve this then go ahead with the PR.

**Comment by thisrahul** [comment]
Okay

**Comment by avidraghav** [comment]
Please reopen and continue with the last PR, their is no point of making another PR

**Comment by thisrahul** [comment]
Yes , I reopen

**Comment by thisrahul** [comment]
and i close pr because i am waiting for your reply thats why not any other reason.

**Comment by avidraghav** [comment]
After you raise a PR, then it's upto the maintainer to merge it or ask for changes. So only raise a PR when you have completed the task. Still if some changes have to be made after raising the PR then first mark the PR as a draft then make those changes.

**Comment by thisrahul** [comment]
Okay,I will keep in mind for future and thanks for your suggestions.

**Comment by avidraghav** [comment]
The whole purpose of this exercise is to make you knowledgable about github practices, glad i'm helping :)

**Comment by thisrahul** [comment]
Yes,Thanks a lot
Actually its my first time open source contribution that's why i think i am making these silly mistakes

**Comment by thisrahul** [comment]
Hello sir,when you are merge this pr so i can give new pr for other issue

**Comment by avidraghav** [comment]
You can raise the PR for both issues at the same time, i'll merge it soon as I get the time.

**Comment by avidraghav** [comment]
implemented in #59
