### ISSUE TITLE
Implement Animations for various transitions

### ISSUE THREAD

**Issue by avidraghav** [avidraghav/MyNotes#50]
Implement animated transitions for various actions such as 
1. When a user clicks on add note/todo button and moves to the next screen where he fills the details of that note/todo.
2. Initially when the user opens the app the already saved notes/todo should have a descent and simple entry animation.

**Comment by thisrahul** [comment]
Can you please assign this to me?

**Comment by avidraghav** [comment]
Assigned :)

**Comment by thisrahul** [comment]
Thank you

**Comment by thisrahul** [comment]
Hello sir , i will add slide in slide out animation for actions please check the video below:

https://user-images.githubusercontent.com/52368582/193450428-a6920ad2-8771-427b-af76-87fb50d646e8.mp4

**Comment by avidraghav** [comment]
Looks good, please add appropriate animation when the Note is saved. Also can u add a descent entry animation for already saved notes?

**Comment by thisrahul** [comment]
Yes,looking for animation to fit for entry animation

**Comment by avidraghav** [comment]
When can I expect a PR for this task? Any ETA?

**Comment by thisrahul** [comment]
By today EOD currently looking for better transition thats why not giving till now

**Comment by thisrahul** [comment]
Hello sir,Good evening 
here is a small video of entry animation,all note to add note animation

https://user-images.githubusercontent.com/52368582/193611197-ec37eac0-744e-4d92-857e-9ae128ef929c.mp4

**Comment by avidraghav** [comment]
Animations looks cool, go ahead :)

**Comment by thisrahul** [comment]
Sir its final like the entry animation and add note button click to add fragment animation and recyclerview item click to add fragment animation 
Somewhere i need to add any animation?

**Comment by avidraghav** [comment]
Yup animations look good, just make sure that the animation resource files which you'll add should not be too big in size.

**Comment by thisrahul** [comment]
its size around 600B

**Comment by avidraghav** [comment]
Go forward.
