### ISSUE TITLE
Improve the overall UI of the app

### ISSUE THREAD

**Issue by avidraghav** [avidraghav/MyNotes#57]
The styling of Shown Tasks is very basic, improve it by changing the delete icon style, font style etc.

<img width="407" alt="Screenshot 2022-03-20 at 4 22 26 PM" src="https://user-images.githubusercontent.com/49483235/159158846-e3bbd973-a2d1-46ec-a8d4-54a5d4f4bbd1.png">
 
The above image is just an example, the complete UI of the app needs to be revamped, a descent color scheme and UI needs to be implemented uniformly through the app by following Material guidelines

**Comment by Krish-Parekh** [comment]
Hey @avidraghav  i would like to work on this issue can you assign it to me ?

**Comment by avidraghav** [comment]
sure, assigned :)

**Comment by avidraghav** [comment]
Please share the design and changes you wish to implement here.

**Comment by Krish-Parekh** [comment]
Okay, I was considering switching the EditText box to OutlinedEditText and changing the font family to Poppins.

**Comment by Krish-Parekh** [comment]
While cloning this project, I ran into a problem where XML preview was not appearing with error : 

> Failed to initalize editor

 as a result, I had to upgrade AGP for this project, and it is now operational.

**Comment by avidraghav** [comment]
The problem may not be due to AGP but still to which version did u upgrade?

**Comment by Krish-Parekh** [comment]
> AGP v7.3.0

**Comment by Krish-Parekh** [comment]
![image](https://user-images.githubusercontent.com/73629899/193836356-bc08c3d7-f9b0-4461-93e6-a042b24bb4a7.png)
Hey @avidraghav in this project  newer version for a lot of library I available shouldn't we upgrade? 

- Problem which I faced
- Getting error in fragment add_to_task related to navigation  :  [Android studio build error in navigation component, action is not abstract and does not implement abstract member actionID](https://stackoverflow.com/questions/67609911/android-studio-build-error-in-navigation-component-action-is-not-abstract-and-d)

To Solve that error
- I have upgraded the navigation to version 2.5.2 to fix that bug.

**Comment by Krish-Parekh** [comment]
Cool, I'll add animation. Does this user interface look good? Do you have any suggestions, and one more thing: If I submit a PR request, should I include all the modifications because I had to update a few versions to make this project function, or should I simply upload files pertaining to the user interface?

**Comment by avidraghav** [comment]
Can you change the color scheme of the app too? A descent one perhaps.
Yeah include the dependency changes too, can you please make seperate commits for dependency updates?

**Comment by Krish-Parekh** [comment]
Hey @avidraghav I added lottie animation, and the file size is 30 KB. After this I will start working on color scheme

https://user-images.githubusercontent.com/73629899/194003930-acf18502-9245-4be5-b892-5ca520cff26b.mp4

**Comment by avidraghav** [comment]
Looks good :)

**Comment by Krish-Parekh** [comment]
<table>
<tr>
  <th> All Task Fragment </th>
  <th> Add Task Fragment </th>
  <th> Calendar View </th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/73629899/194023768-3ab4e63d-2c3a-41fd-af79-e592f167fb34.jpeg"/>
</td>
<td>
<img src="https://user-images.githubusercontent.com/73629899/194023764-26906bb2-f4d4-4ed5-ba49-fbb0310ef436.jpeg" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/73629899/194023771-e17ecaad-d084-4a1b-9adf-4aa31951fe24.jpeg"
 /></td>
</tr>
</table>

I have changed our UI color

**Comment by avidraghav** [comment]
Looks neat :)
