### ISSUE TITLE
Improve ui

### ISSUE THREAD

**Issue by thisrahul** [avidraghav/MyNotes#64]
@avidraghav Sir can i improve all fragment recyclerview item layout below is the reference image of improvement like its not exact because screenshot is of another ui but improve in same way.

![WhatsApp Image 2022-10-05 at 7 48 59 PM](https://user-images.githubusercontent.com/52368582/194083757-d625a1c2-0154-4085-b602-a5f4d3558d7b.jpeg)

**Comment by thisrahul** [comment]
Hello @avidraghav  sir can i start work on this if you find good issue to be improve

**Comment by avidraghav** [comment]
Sure, please make a branch from Master and share the design you wish to implement

**Comment by thisrahul** [comment]
Hello sir ,can you please confirm so i give pr

**Comment by avidraghav** [comment]
Looks good, do add a ripple effect to the delete button :)

**Comment by thisrahul** [comment]
Okay

**Comment by avidraghav** [comment]
closed by #69
