### ISSUE TITLE
Parcelable vs Serializable

### ISSUE THREAD

**Issue by Krish-Parekh** [avidraghav/MyNotes#66]
Shouldn't we use Parcelable instead of Serializable in our [TaskEntity](https://github.com/avidraghav/MyNotes/blob/master/app/src/main/java/com/raghav/mynotes/models/TaskEntity.kt); parceable process is much faster than serializable, I was reading about the difference between them and I found this [StackOverFlow](https://stackoverflow.com/questions/3323074/android-difference-between-parcelable-and-serializable)

**Comment by avidraghav** [comment]
Yes, definitely. Please Go ahead with the Parcelable implementation.
