### ISSUE TITLE
Clean up code with Dispatchers

### ISSUE THREAD

**Issue by NewtonCesarRoncari** [avidraghav/MyNotes#68]
When running a sonar lint in code, issues arise about the unnecessary Dispatchers when call suspend functions

![Captura de Tela 2022-10-06 às 19 18 35](https://user-images.githubusercontent.com/31870695/194431258-c56aba5a-ffd2-42e2-a3a7-fb8a8cd798e3.png)
![Captura de Tela 2022-10-06 às 19 35 51](https://user-images.githubusercontent.com/31870695/194431270-8216c1dd-3925-48db-9a81-45a80b1a3203.png)

can i improve these parts ?

**Comment by avidraghav** [comment]
Can you send me the screenshot of the code itself where the Lint is giving warnings?

**Comment by NewtonCesarRoncari** [comment]
of Course

AddTaskVM
![Captura de Tela 2022-10-07 às 09 37 30](https://user-images.githubusercontent.com/31870695/194555338-04a35835-6bbe-4d2f-bcc6-982869c88a9f.png)
AllTasksVM
![Captura de Tela 2022-10-07 às 09 36 52](https://user-images.githubusercontent.com/31870695/194555463-dea8005d-9c37-43c2-8a14-108306d3eae9.png)

**Comment by NewtonCesarRoncari** [comment]
you don't need a dispatcher in **launch** to call a **suspend function**, I removed the dispatchers and the app worked normally, you can chack here ( [S6307: Suspending functions should be main-safe](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#viewmodel-coroutines) )

![Captura de Tela 2022-10-07 às 12 41 51](https://user-images.githubusercontent.com/31870695/194594127-41bbda4e-ce73-45fa-9e0e-d2729e5e7730.png)
![Captura de Tela 2022-10-07 às 12 42 47](https://user-images.githubusercontent.com/31870695/194594138-c65dcb40-37cb-4951-b76f-4e8c21034ee5.png)

Notice that the **getTask** method doesn't show the dispatcher's lint warning because it doesn't call a suspend function

![Captura de Tela 2022-10-07 às 12 42 06](https://user-images.githubusercontent.com/31870695/194594449-b6848835-652e-458e-986f-2516dc56f22a.png)

**Comment by avidraghav** [comment]
Try running the tests in `AllTasksVMTest` class and you will see they will all fail. For writing unit tests for functions which use `viewModelScope` it's necessary to provide a test dispatcher as Main Looper which is used by Dispatcher.Main is not available for unit tests. 
One can also hack the dispatcher by using Dispatcher.setMain but injecting dispatchers is the recommended way.

**Comment by NewtonCesarRoncari** [comment]
Ok, i will not work on dispatchers
but i found a bug when keyboar stays over the sanckbar when the user, dont select a deadline, can i work on this ?

https://user-images.githubusercontent.com/31870695/194714442-deb82977-2e78-4056-af30-f6781bc94e9f.mp4

**Comment by avidraghav** [comment]
Yes this looks like a valid issue. Please raise another issue and I'll assign that to you
