### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by aritra-tech** [avidraghav/MyNotes#71]
Splash screen will looks great at the time of opening the app

**Comment by avidraghav** [comment]
Hi, yes spalsh screen will be good but how you wish to implement the same?

**Comment by aritra-tech** [comment]
We can use lottie animation or the app logo

**Comment by avidraghav** [comment]
Yeah we but in that case you will not learn anything. I'm accepting contributions for the sake of enhancement of the app and making contributors learn new and important Android concepts. How about using the [Jetpack Splash Screen Library](https://developer.android.com/develop/ui/views/launch/splash-screen)

**Comment by aritra-tech** [comment]
> Yeah we but in that case you will not learn anything. I'm accepting contributions for the sake of enhancement of the app and making contributors learn new and important Android concepts. How about using the [Jetpack Splash Screen Library](https://developer.android.com/develop/ui/views/launch/splash-screen)

I don't know Jetpack compose , but I will try to use it

**Comment by avidraghav** [comment]
No, This doesn't requires Jetpack Compose. 
Have you done android development before?

**Comment by aritra-tech** [comment]
> No, This doesn't requires Jetpack Compose.

Oo ok then
