### ISSUE TITLE
Update Demo Video in Readme

### ISSUE THREAD

**Issue by avidraghav** [avidraghav/MyNotes#77]
Replace the App demo video displayed in Readme with the latest Version.

**Comment by thisrahul** [comment]
can i do this

**Comment by thisrahul** [comment]
![demo_video](https://user-images.githubusercontent.com/52368582/195093489-f8ffa813-b39c-4275-81af-d07208cac117.gif)

**Comment by thisrahul** [comment]
here is video that i replace

**Comment by avidraghav** [comment]
closed by #79
