### ISSUE TITLE
Automated testing 

### ISSUE THREAD

**Issue by Krish-Parekh** [avidraghav/MyNotes#82]
Hey @avidraghav , how did you set up automated testing so that whenever someone commits to your code, it runs those tests and generates the report? Could you explain it step by step, or if you have any resources on this? Is there anything else I should know before setting up a CI/CD pipeline?

**Comment by avidraghav** [comment]
It took me some iterations to make the required CI/CD pipeline. I followed a blog/tutorial from RayWenderlich way back  and can't remember exactly the author. But you may search from the same website.

**Comment by avidraghav** [comment]
closing it for now
